# Generated by Django 3.1.1 on 2020-12-22 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_unitofhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor', '0006_auto_20200917_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('basemodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.basemodels')),
                ('code', models.CharField(max_length=20)),
                ('max_uses_limit', models.IntegerField()),
                ('max_limit_per_user', models.IntegerField(default=1)),
                ('value', models.IntegerField()),
                ('min_amount', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('use_count', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_creator', to='vendor.vendor')),
            ],
            bases=('accounts.basemodels',),
        ),
        migrations.CreateModel(
            name='UserPromoCode',
            fields=[
                ('basemodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.basemodels')),
                ('discounted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_payment_success', models.BooleanField(default=False)),
                ('payment_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.unitofhistory')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.promo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='used_promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounts.basemodels',),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('basemodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.basemodels')),
                ('full_name', models.CharField(max_length=155)),
                ('phone', models.CharField(max_length=15)),
                ('address_line_1', models.CharField(max_length=120)),
                ('city', models.CharField(default='Dhaka', max_length=120)),
                ('country', models.CharField(default='Bangladesh', max_length=120)),
                ('postal_code', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_address', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounts.basemodels',),
        ),
    ]
