# Generated by Django 3.1.1 on 2020-12-08 06:14

from django.db import migrations
import image_optimizer.fields
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201208_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_thumbnail',
            field=image_optimizer.fields.OptimizedImageField(blank=True, upload_to=product.models.upload_image_path),
        ),
    ]
