# Generated by Django 3.1.1 on 2020-09-16 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_remove_stock_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='product',
            new_name='item',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productattribute',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='size',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_name',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
