# Generated by Django 3.1.1 on 2020-12-22 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0006_basemodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, help_text='The name of the content from which this unit of history is generated', max_length=255, null=True, verbose_name='Name of Content')),
                ('description', models.CharField(blank=True, help_text='From where this unit of history is generated', max_length=255, null=True, verbose_name='Description of Content')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
