# Generated by Django 3.1.1 on 2020-12-15 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0006_auto_20200917_1010'),
        ('accounts', '0006_basemodels'),
        ('product', '0004_item_image_thumbnail'),
        ('customer', '0004_auto_20200920_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('basemodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.basemodels')),
                ('full_name', models.CharField(max_length=155)),
                ('phone', models.CharField(max_length=15)),
                ('address_line_1', models.CharField(max_length=120)),
                ('city', models.CharField(default='Dhaka', max_length=120)),
                ('country', models.CharField(default='Bangladesh', max_length=120)),
                ('postal_code', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_address', to='customer.customer')),
            ],
            bases=('accounts.basemodels',),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('basemodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.basemodels')),
                ('code', models.CharField(max_length=20)),
                ('max_uses_limit', models.IntegerField()),
                ('max_limit_per_user', models.IntegerField(default=1)),
                ('value', models.IntegerField()),
                ('min_amount', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('use_count', models.IntegerField()),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_creator', to='vendor.vendor')),
            ],
            bases=('accounts.basemodels',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('basemodels_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.basemodels')),
                ('order_id', models.CharField(blank=True, max_length=15, null=True)),
                ('cart_total', models.DecimalField(decimal_places=5, default=0.0, max_digits=9, max_length=9)),
                ('status', models.CharField(choices=[('payment pending', 'Payment Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=15)),
                ('shipping_method', models.CharField(choices=[('home delivery', 'Home Delivery'), ('office pick', 'Office Pick')], default='home delivery', max_length=15)),
                ('shipping_total', models.DecimalField(decimal_places=5, default=0.0, max_digits=9, max_length=9)),
                ('total', models.DecimalField(decimal_places=5, default=0.0, max_digits=9, max_length=9)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_customer', to='customer.customer')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_promo', to='ordermanager.promo')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipping_address', to='ordermanager.address')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_vendor', to='vendor.vendor')),
            ],
            bases=('accounts.basemodels',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=5, default=0.0, max_digits=9, max_length=9)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_total', models.DecimalField(blank=True, decimal_places=5, default=0.0, max_digits=9, max_length=9, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='ordermanager.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_product', to='product.product')),
            ],
        ),
    ]
