# Generated by Django 3.1.1 on 2020-12-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanager', '0003_auto_20201215_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
