# Generated by Django 3.1.1 on 2020-12-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanager', '0005_auto_20201215_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
    ]
