# Generated by Django 3.1.1 on 2020-12-22 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ordermanager', '0007_auto_20201222_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='basemodels_ptr',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='creator',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipping_address', to='core.address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Promo',
        ),
    ]
