# Generated by Django 3.1.1 on 2020-12-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanager', '0008_auto_20201222_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('rejected', 'Rejected'), ('payment pending', 'Payment Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='created', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('rejected', 'Rejected'), ('payment pending', 'Payment Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='created', max_length=15),
        ),
    ]
